language: php

sudo: false

matrix:
  include:
    - php: 5.6
    - php: 7.0
  fast_finish: true

before_install:
    - composer self-update

install:
  - composer install 

script: vendor/bin/phpunit
